
projection_size: 256
nheads: 8
dropout: 0.05
mlp_amplifier: 4
stage_depths: [3, 3, 3, 3]
input_size: [2, 32, 64, 128]
dim_size: [32, 64, 128, 256]
output_size: [576, 384, 384, 256]
patch_size: [1, 3, 2, 3]
num_patches: [18, 6, 3, 1]
aggregate: True
residual: True
stage3_partition: head-upper-lower